name: usa-new-england

on:
  workflow_dispatch:
  workflow_run:
    workflows: [start map builds]
    types:
      - completed

jobs:
  build:
    uses: ./.github/workflows/reusable-map-build.yml
    with:
      countrycode: US
      maps: |
        [
          {"name":"connecticut","url":"https://download.geofabrik.de/north-america/us/connecticut-latest.osm.pbf","state":"0900"},
          {"name":"maine","url":"https://download.geofabrik.de/north-america/us/maine-latest.osm.pbf","state":"2300"},
          {"name":"massachusetts","url":"https://download.geofabrik.de/north-america/us/massachusetts-latest.osm.pbf","state":"2500"},
          {"name":"new-hampshire","url":"https://download.geofabrik.de/north-america/us/new-hampshire-latest.osm.pbf","state":"3300"},
          {"name":"rhode-island","url":"https://download.geofabrik.de/north-america/us/rhode-island-latest.osm.pbf","state":"4400"},
          {"name":"vermont","url":"https://download.geofabrik.de/north-america/us/vermont-latest.osm.pbf","state":"5000"}
        ]
      variants: |
        [
          {"id":"no-street-names","drop_names":true,"include_water":false,"include_green":false,"tag_file":"tags_minimal_street_only.xml"},
          {"id":"with-street-names","drop_names":false,"include_water":false,"include_green":false,"tag_file":"tags_minimal_street_only.xml"},
          {"id":"with-water","drop_names":false,"include_water":true,"include_green":false,"tag_file":"tags_with_water.xml"},
          {"id":"with-green-stuff","drop_names":false,"include_water":false,"include_green":true,"tag_file":"tags_with_green_stuff.xml"}
        ]
